// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsAppUsingRepo.Models;

namespace SportsAppUsingRepo.Migrations
{
    [DbContext(typeof(SportsDbContext))]
    partial class SportsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SportsAppUsingRepo.Models.Test", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.HasKey("ID");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("SportsAppUsingRepo.Models.TestType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("TestTypes");
                });

            modelBuilder.Entity("SportsAppUsingRepo.Models.TestTypeMapper", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TestID");

                    b.Property<int>("TestTypeID");

                    b.HasKey("ID");

                    b.HasIndex("TestID")
                        .IsUnique();

                    b.HasIndex("TestTypeID");

                    b.ToTable("TestTypeMappers");
                });

            modelBuilder.Entity("SportsAppUsingRepo.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Role");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SportsApSportsAppUsingRepoplication.Models.UserTestMapper", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("CooperTestDistance");

                    b.Property<string>("FitnessRating");

                    b.Property<int?>("SprintTestTime");

                    b.Property<int>("TestID");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("TestID");

                    b.HasIndex("UserID");

                    b.ToTable("UserTestMappers");
                });

            modelBuilder.Entity("SportsAppUsingRepo.Models.TestTypeMapper", b =>
                {
                    b.HasOne("SportsAppUsingRepo.Models.Test", "Test")
                        .WithOne("TestTypeMapper")
                        .HasForeignKey("SportsAppUsingRepo.Models.TestTypeMapper", "TestID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SportsAppUsingRepo.Models.TestType", "TestType")
                        .WithMany("TestTypeMapper")
                        .HasForeignKey("TestTypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SportsApSportsAppUsingRepoplication.Models.UserTestMapper", b =>
                {
                    b.HasOne("SportsAppUsingRepo.Models.Test", "Test")
                        .WithMany("UserTestMappers")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SportsAppUsingRepo.Models.User", "User")
                        .WithMany("UserTestMappers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
